In [1]:
import numpy as np
import scipy as sp
from scipy import linalg

In [4]:
# к определению унитарного оператора
U_hat = np.array([
    [1 + 0j, 0 + 0j],
    [0 + 0j, 1 + 0j]
    ])

U_hat_star_byhands = U_hat.conj().T
U_hat_star_long = np.conjugate(np.transpose(U_hat))

print(np.allclose(U_hat_star_long, U_hat_star_byhands))

True


In [3]:
U_hat_star_byhands

array([[1.-0.j, 0.-0.j],
       [0.-0.j, 1.-0.j]])

In [7]:
# любой эрмитов оператор приводится у унитарному через экспоненту
N = 3
w = np.sqrt(np.exp(-1j * 2 * np.pi / N))

D = np.array([
    [1, 1, 1],
    [1, w, w ** 2],
    [1, w ** 2, w ** 4]
    ])

U = D @ D.conj().T
print(f"{U = }")

print(f"{D = }")
print(f"{np.allclose(U @ U.T.conj(), np.eye(N)) = }") # no

U_hat = linalg.expm(1j * U)
print(f"\n{np.allclose(U_hat @ U_hat.conj().T, np.eye(N)) = }")
print(f"\n{np.allclose(U_hat.conj().T @ U_hat, np.eye(N)) = }")

U = array([[ 3.00000000e+00+0.00000000e+00j,  1.00000000e+00+1.73205081e+00j,
        -3.33066907e-16+3.33066907e-16j],
       [ 1.00000000e+00-1.73205081e+00j,  3.00000000e+00-2.97483363e-17j,
         1.00000000e+00+1.73205081e+00j],
       [-3.33066907e-16-3.33066907e-16j,  1.00000000e+00-1.73205081e+00j,
         3.00000000e+00+3.66514617e-17j]])
D = array([[ 1. +0.j       ,  1. +0.j       ,  1. +0.j       ],
       [ 1. +0.j       ,  0.5-0.8660254j, -0.5-0.8660254j],
       [ 1. +0.j       , -0.5-0.8660254j, -0.5+0.8660254j]])
np.allclose(U @ U.T.conj(), np.eye(N)) = False

np.allclose(U_hat @ U_hat.conj().T, np.eye(N)) = True

np.allclose(U_hat.conj().T @ U_hat, np.eye(N)) = True


In [22]:
# есть возможность указать индекс диагонали
print(f"{np.eye(3, k=-1, dtype=int) = }")


np.eye(3, k=-1, dtype=int) = array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])


In [33]:
print(np.linalg.eig(np.diag((1, 2, 3))))

(array([1., 2., 3.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [32]:
M

array([[1., 0., 0.],
       [1., 1., 0.],
       [0., 1., 1.]])